//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metroit.Windows.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metroit.Windows.Forms.Properties.DesignResources", typeof(DesignResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Allow All に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsAll {
            get {
                return ResourceManager.GetString("AcceptsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て許可 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsAll_ja {
            get {
                return ResourceManager.GetString("AcceptsAll.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alpha に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsAlpha {
            get {
                return ResourceManager.GetString("AcceptsAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsAlpha_ja {
            get {
                return ResourceManager.GetString("AcceptsAlpha.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsFull {
            get {
                return ResourceManager.GetString("AcceptsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsFull_ja {
            get {
                return ResourceManager.GetString("AcceptsFull.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Half に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsHalf {
            get {
                return ResourceManager.GetString("AcceptsHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsHalf_ja {
            get {
                return ResourceManager.GetString("AcceptsHalf.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsNum {
            get {
                return ResourceManager.GetString("AcceptsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数字 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsNum_ja {
            get {
                return ResourceManager.GetString("AcceptsNum.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sign に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsSign {
            get {
                return ResourceManager.GetString("AcceptsSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptsSign_ja {
            get {
                return ResourceManager.GetString("AcceptsSign.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This event occurs when the dropdown closes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateBoxClosed {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateBoxClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドロップダウンが閉じた時に発生するイベントです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateBoxClosed_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateBoxClosed.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This event occurs when a dropdown is opened. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateBoxOpened {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateBoxOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドロップダウンが開いた時に発生するイベントです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateBoxOpened_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateBoxOpened.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This event occurs before the dropdown opens. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateBoxOpening {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateBoxOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドロップダウンが開く前に発生するイベントです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateBoxOpening_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateBoxOpening.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is an event that occurs when candidate values are selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateSelected {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   候補の値が選択された時に発生するイベントです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCandidateSelected_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCandidateSelected.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the option to decide candidate narrowing down. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCompareOptions {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCompareOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   候補の絞込みに判断するオプションを取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxCompareOptions_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxCompareOptions.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data binding of the control. You can bind a DataSource. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxDataBindings {
            get {
                return ResourceManager.GetString("AutoCompleteBoxDataBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールのデータバインドです。DataSource をバインドすることができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxDataBindings_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxDataBindings.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the data source including all data used for autocomplete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxDataSource {
            get {
                return ResourceManager.GetString("AutoCompleteBoxDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オートコンプリートに利用される全データを含むデータソースを取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxDataSource_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxDataSource.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicates the properties to display for items in this control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxDisplayMember {
            get {
                return ResourceManager.GetString("AutoCompleteBoxDisplayMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このコントロール内の項目に対して表示するプロパティを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxDisplayMember_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxDisplayMember.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get or set a pattern to narrow down candidates. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxMatchPattern {
            get {
                return ResourceManager.GetString("AutoCompleteBoxMatchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   候補の絞込みを行うパターンを取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxMatchPattern_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxMatchPattern.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the number of items to display in Autocomplete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxMaxDropDownItems {
            get {
                return ResourceManager.GetString("AutoCompleteBoxMaxDropDownItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   オートコンプリートの表示するアイテム数を設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxMaxDropDownItems_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxMaxDropDownItems.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicates the property to use as the actual value for the item in the control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxValueMember {
            get {
                return ResourceManager.GetString("AutoCompleteBoxValueMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロール内のアイテムに対して、実際の値として使用するプロパティを示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AutoCompleteBoxValueMember_ja {
            get {
                return ResourceManager.GetString("AutoCompleteBoxValueMember.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicates whether input of a negative value is permitted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAcceptNegative {
            get {
                return ResourceManager.GetString("ControlAcceptNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイナス値の入力を許可するかどうかを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAcceptNegative_ja {
            get {
                return ResourceManager.GetString("ControlAcceptNegative.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets / sets whether or not to accept NULL input. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAcceptNull {
            get {
                return ResourceManager.GetString("ControlAcceptNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NULLの入力を受け入れるかどうかを取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAcceptNull_ja {
            get {
                return ResourceManager.GetString("ControlAcceptNull.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets the type of input permitted characters. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAcceptsChar {
            get {
                return ResourceManager.GetString("ControlAcceptsChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力許可文字の種類を設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAcceptsChar_ja {
            get {
                return ResourceManager.GetString("ControlAcceptsChar.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets whether to shift the focus to the next control when it is done up to the maximum input. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAutoFocus {
            get {
                return ResourceManager.GetString("ControlAutoFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大入力まで行われた時、次のコントロールへフォーカスを遷移するかを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlAutoFocus_ja {
            get {
                return ResourceManager.GetString("ControlAutoFocus.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the background color of the control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBaseBackColor {
            get {
                return ResourceManager.GetString("ControlBaseBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールの背景色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBaseBackColor_ja {
            get {
                return ResourceManager.GetString("ControlBaseBackColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the frame color of the control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBaseBorderColor {
            get {
                return ResourceManager.GetString("ControlBaseBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールの枠色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBaseBorderColor_ja {
            get {
                return ResourceManager.GetString("ControlBaseBorderColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the foreground color of the control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBaseForeColor {
            get {
                return ResourceManager.GetString("ControlBaseForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールの前景色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlBaseForeColor_ja {
            get {
                return ResourceManager.GetString("ControlBaseForeColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the character encoding that implements the maximum byte limit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlByteEncoding {
            get {
                return ResourceManager.GetString("ControlByteEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大バイト数制限を実施する文字エンコーディングを指定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlByteEncoding_ja {
            get {
                return ResourceManager.GetString("ControlByteEncoding.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents the symbol when currency is expressed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlCurrencySymbol {
            get {
                return ResourceManager.GetString("ControlCurrencySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通貨表現の時の記号を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlCurrencySymbol_ja {
            get {
                return ResourceManager.GetString("ControlCurrencySymbol.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When the character type is custom, set a single character to be entered on a line-by-line basis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlCustomChars {
            get {
                return ResourceManager.GetString("ControlCustomChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字種類がカスタムな場合に、入力を許可する単一文字を1行単位で設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlCustomChars_ja {
            get {
                return ResourceManager.GetString("ControlCustomChars.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The current date and time value for this control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlDateTimeValue {
            get {
                return ResourceManager.GetString("ControlDateTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このコントロールの現在の日付/時間の値です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlDateTimeValue_ja {
            get {
                return ResourceManager.GetString("ControlDateTimeValue.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents the number of decimal places that can be entered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlDecimalDigits {
            get {
                return ResourceManager.GetString("ControlDecimalDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力可能な小数桁数を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlDecimalDigits_ja {
            get {
                return ResourceManager.GetString("ControlDecimalDigits.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents the delimiter between the integer part and the decimal part. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlDecimalSeparator {
            get {
                return ResourceManager.GetString("ControlDecimalSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数部と小数部の区切り文字を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlDecimalSeparator_ja {
            get {
                return ResourceManager.GetString("ControlDecimalSeparator.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set whether to shift the focus when the Enter key is pressed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlEnterFocus {
            get {
                return ResourceManager.GetString("ControlEnterFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enterキーが押された時にフォーカスを遷移するかを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlEnterFocus_ja {
            get {
                return ResourceManager.GetString("ControlEnterFocus.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets whether the control is error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlError {
            get {
                return ResourceManager.GetString("ControlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールがエラーかどうかを取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlError_ja {
            get {
                return ResourceManager.GetString("ControlError.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the frame color of control at error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlErrorBorderColor {
            get {
                return ResourceManager.GetString("ControlErrorBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー時のコントロールの枠色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlErrorBorderColor_ja {
            get {
                return ResourceManager.GetString("ControlErrorBorderColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the behavior when the ESC key is pressed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlEscPush {
            get {
                return ResourceManager.GetString("ControlEscPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESCキーが押された時の振る舞いを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlEscPush_ja {
            get {
                return ResourceManager.GetString("ControlEscPush.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set a single character to reject input on a line-by-line basis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlExcludeChars {
            get {
                return ResourceManager.GetString("ControlExcludeChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力を拒否する単一文字を1行単位で設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlExcludeChars_ja {
            get {
                return ResourceManager.GetString("ControlExcludeChars.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the background color of the control at focus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusBackColor {
            get {
                return ResourceManager.GetString("ControlFocusBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーカス時のコントロールの背景色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusBackColor_ja {
            get {
                return ResourceManager.GetString("ControlFocusBackColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the frame color of the control at focus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusBorderColor {
            get {
                return ResourceManager.GetString("ControlFocusBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーカス時のコントロールの枠色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusBorderColor_ja {
            get {
                return ResourceManager.GetString("ControlFocusBorderColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the foreground color of the control at focus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusForeColor {
            get {
                return ResourceManager.GetString("ControlFocusForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーカス時のコントロールの前景色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusForeColor_ja {
            get {
                return ResourceManager.GetString("ControlFocusForeColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sets whether to invert text when getting focus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusSelect {
            get {
                return ResourceManager.GetString("ControlFocusSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーカスを得た時、テキストを反転させるかを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFocusSelect_ja {
            get {
                return ResourceManager.GetString("ControlFocusSelect.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close the form. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFormClose {
            get {
                return ResourceManager.GetString("ControlFormClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォームを閉じます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFormClose_ja {
            get {
                return ResourceManager.GetString("ControlFormClose.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Separately specify the double-byte symbols to be set on a line-by-line basis. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFullSignSpecialChars {
            get {
                return ResourceManager.GetString("ControlFullSignSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個別で許可する全角記号を1行単位で設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlFullSignSpecialChars_ja {
            get {
                return ResourceManager.GetString("ControlFullSignSpecialChars.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents a digit separator character in the integer part. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlGroupSeparator {
            get {
                return ResourceManager.GetString("ControlGroupSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数部の桁区切り文字を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlGroupSeparator_ja {
            get {
                return ResourceManager.GetString("ControlGroupSeparator.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents the number of delimited digits in the integer part. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlGroupSizes {
            get {
                return ResourceManager.GetString("ControlGroupSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数部の区切り桁数を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlGroupSizes_ja {
            get {
                return ResourceManager.GetString("ControlGroupSizes.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deactivate the control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlLeave {
            get {
                return ResourceManager.GetString("ControlLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールを非アクティブにします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlLeave_ja {
            get {
                return ResourceManager.GetString("ControlLeave.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the maximum number of bytes that can be entered in the edit control. If 0 is specified, it is unlimited. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMaxByteLength {
            get {
                return ResourceManager.GetString("ControlMaxByteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エディット コントロールに入力できる最大バイト数を指定します。0を指定した場合、無制限となります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMaxByteLength_ja {
            get {
                return ResourceManager.GetString("ControlMaxByteLength.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It represents the maximum value that can be entered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMaxValue {
            get {
                return ResourceManager.GetString("ControlMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力可能な最大値を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMaxValue_ja {
            get {
                return ResourceManager.GetString("ControlMaxValue.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   We extend the standard Form and provide a form with some new functions. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMetForm {
            get {
                return ResourceManager.GetString("ControlMetForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   標準Formを拡張し、新たにいくつかの機能を設けたフォームを提供します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMetForm_ja {
            get {
                return ResourceManager.GetString("ControlMetForm.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It represents the minimum value that can be entered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMinValue {
            get {
                return ResourceManager.GetString("ControlMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力可能な最小値を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMinValue_ja {
            get {
                return ResourceManager.GetString("ControlMinValue.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It represents the format displayed when there is no focus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMode {
            get {
                return ResourceManager.GetString("ControlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォーカスがない時に表示される形式を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlMode_ja {
            get {
                return ResourceManager.GetString("ControlMode.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It represents the character color at minus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlNegativeForeColor {
            get {
                return ResourceManager.GetString("ControlNegativeForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイナス時の文字色を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlNegativeForeColor_ja {
            get {
                return ResourceManager.GetString("ControlNegativeForeColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents a symbolic representation when it is a negative number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlNegativePattern {
            get {
                return ResourceManager.GetString("ControlNegativePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   負数の時の記号表現を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlNegativePattern_ja {
            get {
                return ResourceManager.GetString("ControlNegativePattern.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents the sign when it is a negative number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlNegativeSign {
            get {
                return ResourceManager.GetString("ControlNegativeSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   負数の時の記号を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlNegativeSign_ja {
            get {
                return ResourceManager.GetString("ControlNegativeSign.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents the symbol for percent representation. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlPercentSymbol {
            get {
                return ResourceManager.GetString("ControlPercentSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーセント表現の時の記号を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlPercentSymbol_ja {
            get {
                return ResourceManager.GetString("ControlPercentSymbol.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents a symbolic representation when it is a positive number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlPositivePattern {
            get {
                return ResourceManager.GetString("ControlPositivePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正数の時の記号表現を表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlPositivePattern_ja {
            get {
                return ResourceManager.GetString("ControlPositivePattern.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace the control with a text box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlReadOnly {
            get {
                return ResourceManager.GetString("ControlReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールをテキストボックスで置き換えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlReadOnly_ja {
            get {
                return ResourceManager.GetString("ControlReadOnly.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace the control with a label. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlReadOnlyLabel {
            get {
                return ResourceManager.GetString("ControlReadOnlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールをラベルで置き換えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlReadOnlyLabel_ja {
            get {
                return ResourceManager.GetString("ControlReadOnlyLabel.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When implementing the ILeaveRollback interface for this form or each control, roll back control information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlRollback {
            get {
                return ResourceManager.GetString("ControlRollback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このフォームまたはそれぞれのコントロールにILeaveRollback インターフェースを実装している時、コントロールの情報をロールバックします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlRollback_ja {
            get {
                return ResourceManager.GetString("ControlRollback.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The number associated with the control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlValue {
            get {
                return ResourceManager.GetString("ControlValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コントロールに関連付けられた数値です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ControlValue_ja {
            get {
                return ResourceManager.GetString("ControlValue.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Currency Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrencyPattern {
            get {
                return ResourceManager.GetString("CurrencyPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通貨表記時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrencyPattern_ja {
            get {
                return ResourceManager.GetString("CurrencyPattern.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Custom_ja {
            get {
                return ResourceManager.GetString("Custom.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit Extension Appearance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetAppearance {
            get {
                return ResourceManager.GetString("MetAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit拡張 表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetAppearance_ja {
            get {
                return ResourceManager.GetString("MetAppearance.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit Extension Behavior に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetBehavior {
            get {
                return ResourceManager.GetString("MetBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit拡張 動作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetBehavior_ja {
            get {
                return ResourceManager.GetString("MetBehavior.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Represents a Windows control that allows the user to select a date and time, specify the format and display the date and time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetDateTimePicker {
            get {
                return ResourceManager.GetString("MetDateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが日時を選択し、書式を指定して日時を表示できる Windows コントロールを表します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetDateTimePicker_ja {
            get {
                return ResourceManager.GetString("MetDateTimePicker.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This event occurs when ESC key loses focus. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetFormControlLeaving {
            get {
                return ResourceManager.GetString("MetFormControlLeaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESCキーによってフォーカスを失う時に発生するイベントです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetFormControlLeaving_ja {
            get {
                return ResourceManager.GetString("MetFormControlLeaving.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This event occurs when rollback is performed by the ESC key. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetFormControlRollbacking {
            get {
                return ResourceManager.GetString("MetFormControlRollbacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ESCキーによってロールバックを行う時に発生するイベントです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetFormControlRollbacking_ja {
            get {
                return ResourceManager.GetString("MetFormControlRollbacking.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provides a text area with input character type and input byte count limiting function. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetLimitedTextBox {
            get {
                return ResourceManager.GetString("MetLimitedTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力文字種、入力バイト数制限機能を設けたテキストエリアを提供します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetLimitedTextBox_ja {
            get {
                return ResourceManager.GetString("MetLimitedTextBox.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provide a text area that allows users to enter numerical values only. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetNumericTextBox {
            get {
                return ResourceManager.GetString("MetNumericTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーが数値のみを入力できるようにしたテキストエリアを提供します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetNumericTextBox_ja {
            get {
                return ResourceManager.GetString("MetNumericTextBox.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit Extension Other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetOther {
            get {
                return ResourceManager.GetString("MetOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit拡張 その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetOther_ja {
            get {
                return ResourceManager.GetString("MetOther.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit Extension Property Changed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetPropertyChange {
            get {
                return ResourceManager.GetString("MetPropertyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metroit拡張 プロパティ変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetPropertyChange_ja {
            get {
                return ResourceManager.GetString("MetPropertyChange.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set custom autocomplete information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxCustomAutoCompleteBox {
            get {
                return ResourceManager.GetString("MetTextBoxCustomAutoCompleteBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムオートコンプリート情報を設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxCustomAutoCompleteBox_ja {
            get {
                return ResourceManager.GetString("MetTextBoxCustomAutoCompleteBox.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the key to display the custom autocomplete candidate pulldown. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxCustomAutoCompleteDisplayKeys {
            get {
                return ResourceManager.GetString("MetTextBoxCustomAutoCompleteDisplayKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムオートコンプリート候補プルダウンを表示するキーを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxCustomAutoCompleteDisplayKeys_ja {
            get {
                return ResourceManager.GetString("MetTextBoxCustomAutoCompleteDisplayKeys.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set up how to use custom autocomplete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxCustomAutoCompleteMode {
            get {
                return ResourceManager.GetString("MetTextBoxCustomAutoCompleteMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムオートコンプリートの利用方法を設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxCustomAutoCompleteMode_ja {
            get {
                return ResourceManager.GetString("MetTextBoxCustomAutoCompleteMode.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In multi-line text editing, you can set whether to select all text by pressing Ctrl + A. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxMultilineSelectAll {
            get {
                return ResourceManager.GetString("MetTextBoxMultilineSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数行テキストエディットの時、Ctrl+Aを押すことでテキストを全選択するかを設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxMultilineSelectAll_ja {
            get {
                return ResourceManager.GetString("MetTextBoxMultilineSelectAll.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   occurs when the value of the Text property is added or inserted. You can verify the value and reject the change. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxTextChangeValidation {
            get {
                return ResourceManager.GetString("MetTextBoxTextChangeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text プロパティの値が追加／挿入されているときに発生するイベントです。値を検証し、変更を拒否することができます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxTextChangeValidation_ja {
            get {
                return ResourceManager.GetString("MetTextBoxTextChangeValidation.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get or set watermark. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxWatermark {
            get {
                return ResourceManager.GetString("MetTextBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウォーターマークの取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxWatermark_ja {
            get {
                return ResourceManager.GetString("MetTextBoxWatermark.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gets or sets the foreground color of the watermark. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxWatermarkColor {
            get {
                return ResourceManager.GetString("MetTextBoxWatermarkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウォーターマークの前景色を取得または設定します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MetTextBoxWatermarkColor_ja {
            get {
                return ResourceManager.GetString("MetTextBoxWatermarkColor.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numeric Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumericPattern {
            get {
                return ResourceManager.GetString("NumericPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値表記時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NumericPattern_ja {
            get {
                return ResourceManager.GetString("NumericPattern.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Percent Pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PercentPattern {
            get {
                return ResourceManager.GetString("PercentPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーセント表記時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PercentPattern_ja {
            get {
                return ResourceManager.GetString("PercentPattern.ja", resourceCulture);
            }
        }
    }
}
