//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metroit.Windows.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metroit.Windows.Forms.Properties.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Value is negative and can not be changed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptNegativeCanNotChange {
            get {
                return ResourceManager.GetString("AcceptNegativeCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valueが負数のため、変更できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AcceptNegativeCanNotChange_ja {
            get {
                return ResourceManager.GetString("AcceptNegativeCanNotChange.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unacceptable value has been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeniedTextException {
            get {
                return ResourceManager.GetString("DeniedTextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許可されない値が設定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeniedTextException_ja {
            get {
                return ResourceManager.GetString("DeniedTextException.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unacceptable value has been set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   許可されない文字列が設定されました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidValue_ja {
            get {
                return ResourceManager.GetString("InvalidValue.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values larger than MaxValue can not be set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxValueSmallerCanNotChange {
            get {
                return ResourceManager.GetString("MaxValueSmallerCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MaxValueの値より小さい値は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MaxValueSmallerCanNotChange_ja {
            get {
                return ResourceManager.GetString("MaxValueSmallerCanNotChange.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values smaller than MinValue can not be set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinValueSmallerCanNotChange {
            get {
                return ResourceManager.GetString("MinValueSmallerCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MinValueの値より小さい値は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MinValueSmallerCanNotChange_ja {
            get {
                return ResourceManager.GetString("MinValueSmallerCanNotChange.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values larger than Value can not be set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValueLargerCanNotChange {
            get {
                return ResourceManager.GetString("ValueLargerCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valueの値より大きい値は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValueLargerCanNotChange_ja {
            get {
                return ResourceManager.GetString("ValueLargerCanNotChange.ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values smaller than Value can not be set. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValueSmallerCanNotChange {
            get {
                return ResourceManager.GetString("ValueSmallerCanNotChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valueの値より小さい値は設定できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValueSmallerCanNotChange_ja {
            get {
                return ResourceManager.GetString("ValueSmallerCanNotChange.ja", resourceCulture);
            }
        }
    }
}
